POST http://localhost:5001/user/login
Content-Type: application/json

{
  "email": "elice@elice.com",
  "password": "asdfqwer"
}

###
GET http://localhost:5001/projects/4a4d6df2-775a-455c-905f-67bc5fb833fe
